config/routes.rb
MapismoApp::Application.routes.draw do
  root to: "site#home"

  get   '/login',                   to: 'sessions#new', as: :login
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure',            to: 'sessions#failure'
  get   '/logout',                  to: 'sessions#destroy', as: :logout

  get       '/map/:user_id/:id',    to: 'maps#show', as: :map
  post      '/map/preview',         to: 'maps#preview', as: :map_preview
  resources :maps,                  except: [:edit, :update, :show]
end

app/models/map.rb
# coding: UTF-8

class Map
  VALID_SOURCES = %W{ instagram flickr }

  attr_reader :user_id, :keywords, :sources, :radius,
              :end_date, :start_date, :lat, :lon

  attr_accessor :name, :location_name, :id, :preview_token

  def initialize(attributes = {})
    @id = attributes[:id] || nil
    @name = attributes[:name] || ""
    @location_name = attributes[:location_name] || ""
    @preview_token = attributes[:preview_token] || ""

    if attributes[:user_id]
      @user_id = attributes[:user_id].to_i
    else
      raise "User is required"
    end

    self.keywords   = attributes[:keywords]
    self.sources    = attributes[:sources]
    self.radius     = attributes[:radius]
    self.lat        = attributes[:lat]
    self.lon        = attributes[:lon]
    self.start_date = attributes[:start_date]
    self.end_date   = attributes[:end_date]
  end

  def keywords=(value)
    value = [] if value.blank?
    if value.is_a?(String)
      value = value.split(',').map{ |k| k.strip }.compact.flatten
    end
    if value.size > 3
      raise "Only 3 keywords are allowed"
    end
    @keywords = value
  end

  def sources=(value)
    value ||= []
    if value.is_a?(String)
      value = value.split(',').map{ |k| k.strip }.compact.flatten
    end
    value.delete_if{ |v| v.blank? }
    value.each do |source|
      raise "Source #{source} is not allowed" unless VALID_SOURCES.include?(source)
    end
    @sources = value
  end

  def radius=(value)
    value ||= 1_000
    value = value.to_i
    raise "Radius must be a possitive value" if value < 0
    raise "Radius must be a value between 0 and 5000" if value > 5_000
    @radius = value
  end

  def start_date=(value)
    @start_date = validate_date(value)
  end

  def end_date=(value)
    @end_date = validate_date(value)
  end

  def lat=(value)
    @lat = value.nil? ? 0.0 : value.to_f
  end

  def lon=(value)
    @lon = value.nil? ? 0.0 : value.to_f
  end

  def user
    User.find(@user_id)
  end

  # find a map
  # requires :id and :user_id in the attributes
  def self.find(attributes)
    attributes.symbolize_keys!

    raise "Map ID is required" if attributes[:id].blank?
    map_id = attributes[:id].to_i

    raise "User ID or User is required" if attributes[:user_id].blank? && attributes[:user].blank?
    user = attributes[:user_id] ? User.find(attributes[:user_id]) : attributes[:user]

    connection = user.get_connection

    if row = connection.find_row(Mapismo.maps_table, "cartodb_id = #{map_id}")
      new(row_to_attributes(row, user))
    else
      nil
    end
  end

  def save
    @preview_token = nil

    row = {
      name: @name,
      sources: self.sources.join(','),
      keywords: self.keywords.join(','),
      start_date: self.start_date,
      end_date: self.end_date,
      radius: self.radius,
      location_name: self.location_name,
      lat: self.lat,
      lon: self.lon
    }

    connection = self.user.get_connection
    if connection.insert_row(Mapismo.maps_table, row)
      @id = connection.get_id_from_last_record(Mapismo.maps_table)
      notify_workers
      return true
    else
      raise "Error creating map: #{$!}"
    end
  end

  # Send a message to get preview data to the workers
  # In order to get that, map_id must be 0
  # and the previous data for the preview token must have been removed
  def fetch_preview_data!
    @id = 0
    connection = self.user.get_connection
    connection.run_query("DELETE FROM #{Mapismo.data_table} WHERE preview_token = '#{@preview_token}'")
    notify_workers
    return true
  end

  def self.row_to_attributes(row, user)
    {
      id: row["cartodb_id"].to_i,
      name: row["name"],
      user_id: user.id,
      sources: row["sources"],
      keywords: row["keywords"],
      start_date: row["start_date"],
      end_date: row["end_date"],
      radius: row["radius"],
      location_name: row["location_name"],
      lat: row["lat"],
      lon: row["lon"]
    }
  end

  private

  def validate_date(value)
    value = value.to_s
    unless value.blank?
      begin
        value = Time.parse(value)
      rescue
        raise "Invalid date"
      end
    end
    value
  end

  def notify_workers
    user = self.user
    base_message = {
      cartodb_table_name: Mapismo.data_table,
      cartodb_map_id: self.id,
      cartodb_username: user.username,
      cartodb_userid: self.user_id,
      cartodb_auth_token: user.token,
      cartodb_auth_secret: user.secret,
      latitude: self.lat,
      longitude: self.lon,
      radius: self.radius,
      start_date: self.start_date.strftime("%Y-%m-%d+%H:%M:%S"),
      end_date: self.end_date.strftime("%Y-%m-%d+%H:%M:%S"),
      preview_token: @preview_token
    }
    worker_notifier = WorkerNotifier.new

    keywords = self.keywords.blank? ? [""] : self.keywords
    keywords.each do |k|
      self.sources.each do |s|
        case s
          when 'instagram'
            if @preview_token.blank?
              DateRangifier.new(self.start_date, self.end_date).range.each do |dates_range|
                worker_notifier.notify!(base_message.merge(keyword: k, source: s, start_date: dates_range[0].strftime("%Y-%m-%d+%H:%M:%S"), end_date: dates_range[1].strftime("%Y-%m-%d+%H:%M:%S")))
              end
            else
              worker_notifier.notify!(base_message.merge(keyword: k, source: s))
            end
          when 'flickr'
            worker_notifier.notify!(base_message.merge(keyword: k, source: s))
          end
      end
    end
  end

end

app/controllers/maps_controller.rb
# coding: UTF-8

class MapsController < ApplicationController

  before_filter :login_required, except: [:show]
  before_filter :load_map, only: [:edit, :delete]

  def index
    @maps = current_user.maps
  end

  def new
    @map = Map.new(user_id: current_user.id)
  end

  def preview
    @map = Map.new(params[:map].merge(user_id: current_user.id))
    @map.fetch_preview_data!
    respond_to do |format|
      format.js { render nothing: true }
    end
  end

  def create
    @map = Map.new(params[:map].merge(user_id: current_user.id))
    if @map.save
      redirect_to map_path(current_user.id, @map.id), flash: {notice: "Your map has been created successfully"}
    else
      render "new"
    end
  end

  def show
    unless @user = User.find(params[:user_id])
      render_404 and return
    end
    unless @map = Map.find(user_id: @user.id, id: params[:id])
      render_404 and return
    end
  end

  def delete
    @map = Map.find(user_id: current_user.id, id: params[:id])
  end

end

app/views/maps/index.html.erb
<% title "Your maps" %>

<h2>Your maps</h2>

<ul>
<% @maps.each do |map| %>
  <li><%= link_to(map.name, map_path(current_user.id, map.id)) %></li>
<% end %>
</ul>

<p><%= link_to("Create a new map +", new_map_path) %></p>

app/views/maps/show.html.erb
<% title @map.name %>

<%= content_for :head do %>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <link rel="shortcut icon" href="http://cartodb.com/favicon/favicon_32x32.ico" />
  <%= javascript_include_tag "show_map" %>
  <%= javascript_include_tag "//cartodb.s3.amazonaws.com/embed/wax.g.js" %>

  <script type="text/javascript">
    var cartodb_table_name  = "<%= Mapismo.data_table %>",
        cartodb_table_id    = "<%= @user.data_table_id %>",
        cartodb_user_name   = "<%= @user.username %>",
          TILEHTTP = "https",
          TILESERVER = "cartodb.com",
          SQL_SERVER = 'cartodb.com',
          global_api_url = '/api/v1/',
          map_id = '<%= @map.id %>',
          cartodb_sql = escape('SELECT * FROM <%= Mapismo.data_table %> WHERE map_id=<%= @map.id %>'),
          cartodb_style,
          cartodb_params = [];

    $(function() {

      var cartodbMapOptions = {
        zoom: 2,
        center: new google.maps.LatLng(<%= @map.lat %>,<%= @map.lon %>),
        disableDefaultUI: true,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };

      // Init the map
      var carto_embed_map = new google.maps.Map(document.getElementById("map_cartodb_container"),cartodbMapOptions);

      // Setup your map styles
      $.ajax({
        url:TILEHTTP + '://' + cartodb_user_name + '.' + TILESERVER + '/tiles/' + cartodb_table_name + '/map_metadata',
        type: 'GET',
        dataType: 'jsonp',
        success:function(result){
          map_style = $.parseJSON(result.map_metadata);
          if (map_style!=null) {
            if (map_style.google_maps_base_type=="satellite") {
              carto_embed_map.setOptions({mapTypeId: google.maps.MapTypeId.SATELLITE});
            } else if (map_style.google_maps_base_type=="terrain") {
              carto_embed_map.setOptions({mapTypeId: google.maps.MapTypeId.TERRAIN});
            } else {
              carto_embed_map.setOptions({mapTypeId: google.maps.MapTypeId.ROADMAP});
            }

            // Get coordinates and zoom
            if (map_style.zoom && map_style.longitude && map_style.latitude) {
              carto_embed_map.setZoom(map_style.zoom);
            } else {
              getCartoDBBBox(map_id, carto_embed_map);
            }
          } else {
            getCartoDBBBox(map_id, carto_embed_map);
            carto_embed_map.setOptions({mapTypeId: google.maps.MapTypeId.ROADMAP});
            map_style = {};
            map_style.google_maps_customization_style = [ { stylers: [ { saturation: -65 }, { gamma: 1.52 } ] }, { featureType: "administrative", stylers: [ { saturation: -95 },{ gamma: 2.26 } ] }, { featureType: "water", elementType: "labels", stylers: [ { visibility: "off" } ] }, { featureType: "administrative.locality", stylers: [ { visibility: 'off' } ] }, { featureType: "road", stylers: [ { visibility: "simplified" }, { saturation: -99 }, { gamma: 2.22 } ] }, { featureType: "poi", elementType: "labels", stylers: [ { visibility: "off" } ] }, { featureType: "road.arterial", stylers: [ { visibility: 'off' } ] }, { featureType: "road.local", elementType: "labels", stylers: [ { visibility: 'off' } ] }, { featureType: "transit", stylers: [ { visibility: 'off' } ] }, { featureType: "road", elementType: "labels", stylers: [ { visibility: 'off' } ] },{ featureType: "poi", stylers: [ { saturation: -55 } ] } ];
          }

          // Custom tiles
          carto_embed_map.setOptions({styles: map_style.google_maps_customization_style});
        },
        error: function(e){}
      });


      // Necessary params for wax and infowindow
      var cartodb_params = {
            cartodb_sql         : cartodb_sql,
            cartodb_style       : cartodb_style,
            cartodb_user_name   : cartodb_user_name,
            cartodb_table_name  : cartodb_table_name,
            cartodb_table_id    : cartodb_table_id,
            cartodb_map         : carto_embed_map,
            cartodb_map_canvas  : 'map_cartodb_container'
          },
          infowindow = new CartoDBInfowindow(cartodb_params),
          featureList = [], timedFeatures = [],
          timeline = new Timeline();

      loadFeatures();

      function loadFeatures(){
        // Load the list of features
        $.ajax({
          url: TILEHTTP + '://'+cartodb_user_name+'.' + SQL_SERVER + global_api_url+ 'sql/?q='+
                escape('SELECT cartodb_id,date FROM '+ cartodb_table_name + ' WHERE map_id='+map_id+' ORDER BY date ASC'),
          type: 'GET',
          dataType: 'jsonp',
          success:function(result){
            if(result.rows.length > 0){
              $('.progress_bar').hide();
              $('#timeline_bar').show();
              result.rows.forEach(function(row){
                featureList.push(row.cartodb_id);
                timedFeatures.push({id: row.cartodb_id, date: (new Date(row.date.replace('+',' ')).getTime())});
              });
              // Add wax interaction
              addCartoDBInteraction(cartodb_params, infowindow, featureList);

              // Setup timeline
              timeline.setupFeatures(timedFeatures, infowindow, featureList);
            } else {
              $('.progress_bar').show();
              $('#timeline_bar').hide();
              setTimeout(loadFeatures(), 3000);
            }
          }
        });
      }

      // Wax interaction
      function addCartoDBInteraction(params, infowindow, featureList) {
        var currentCartoDbId,
            tilejson = generateTileJson(params),
            cache_buster = 0;

        $('#content nav.pagination a.prev').on({
          click: function(e){
            if(!$(this).hasClass('disabled')){
              var currentFeature = parseInt($('#current_feature').val());
              var index = featureList.indexOf(currentFeature);
              if(index > 0) {
                infowindow.open(featureList[index-1],null,featureList);
              }
            }
            e.preventDefault(); e.stopPropagation();
          }
        });

        $('#content nav.pagination a.next').on({
          click: function(e){
            if(!$(this).hasClass('disabled')){
              currentFeature = $('#current_feature').val();
              var currentFeature = parseInt($('#current_feature').val());
              var index = featureList.indexOf(currentFeature);
              if(index < featureList.length-1) {
                infowindow.open(featureList[index+1],null,featureList);
              }
            }
            e.preventDefault(); e.stopPropagation();
          }
        });

        $('#timeline').on({
          'click': function(e){
            timeline.pause();
            timeline.setPointer(e.clientX - $(this).position().left - 2);
            e.preventDefault(); e.stopPropagation();
          }
        });

        var waxOptions = {
          callbacks: {
            out: function(){
              params.cartodb_map.setOptions({draggableCursor: 'default'});
            },
            over: function(feature, div, opt3, evt){
              params.cartodb_map.setOptions({draggableCursor: 'pointer'});
            },
            click: function(feature, div, opt3, evt){
              infowindow.open(feature,evt.latLng,featureList);
            }
          },
          clickAction: 'full'
        };

        var wax_tile = new wax.g.connector(tilejson);
        params.cartodb_map.overlayMapTypes.insertAt(0,wax_tile);
        var interaction = wax.g.interaction(params.cartodb_map, tilejson, waxOptions);

        // Generate tilejson
        function generateTileJson(params) {
          var core_url = TILEHTTP + '://' + params.cartodb_user_name + '.' + TILESERVER;
          var base_url = core_url + '/tiles/' + params.cartodb_table_name + '/{z}/{x}/{y}';
          var tile_url = base_url + '.png?cache_buster=0&sql=' + params.cartodb_sql;
          var grid_url = base_url + '.grid.json';

          // Build up the tileJSON
          return {
            blankImage: TILEHTTP + '://cartodb.s3.amazonaws.com/embed/blank_tile.png',
            tilejson: '1.0.0',
            scheme: 'xyz',
            tiles: [tile_url],
            grids: [grid_url],
            tiles_base: tile_url,
            grids_base: grid_url,
            formatter: function(options, data) {
                currentCartoDbId = data.cartodb_id;
                return data.cartodb_id;
            },
            cache_buster: function(){
                return params.cache_buster;
            }
          };
        };
      };

      // Zoom bindings
      $('a.cartodb_map_embed_zoom_in').click(function(ev){
        ev.preventDefault();
        carto_embed_map.setZoom(carto_embed_map.getZoom()+1);
      });
      $('a.cartodb_map_embed_zoom_out').click(function(ev){
        ev.preventDefault();
        carto_embed_map.setZoom(carto_embed_map.getZoom()-1);
      });
    });
  </script>

<% end %>

<header id="top_bar">
  <h1>This is a map with <%= @map.name %></h1>
</header>

<div class="progress_bar" style="display:none">
  Still fetching data...
</div>

<div class="popover" id="content" style="display:none">
  <div class="header">
    <nav class="pagination">
      <a href="#" class="prev" title="Previous">Previous item</a>
      <a href="#" class="next" title="Next">Next item</a>
    </nav>

    <div class="item_data">
      <img src="" alt="" class="avatar">
      <p>
        <strong></strong><br>
        <span class="date"></span> · <a href="#" target="blank"></a>
      </p>
    </div>
  </div>
  <div class="content"></div>
  <input type="hidden" id="current_feature" />
</div>

<div id="timeline_bar" style="display:none">
  <a href="#" class="button play">Play</a>
  <div id="timeline_container">
    <div id="timeline">
      <ul class="items"></ul>
    </div>
  </div>
</div>

<div id="outer_map_cartodb_container">
  <div id="map_cartodb_container"></div>
</div>

<span class="cartodb_map_controls">
  <a href="#zoom_in" class="cartodb_map_embed_zoom_in">+</a>
  <a href="#zoom_out" class="cartodb_map_embed_zoom_out">-</a>
</span>